name: Build and Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      run_tests:
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        if: ${{ inputs.run_tests }}
        run: ctest --test-dir build --output-on-failure
