name: CI (Ubuntu)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
      run_tests: true
